apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "premium-lrs-eastus2"
  labels:
    app: grafana
    component: grafana
  name: persistentVolumeClaimNameGrafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
