apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: "kube-state-metrics"
  name: kube-state-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        component: "kube-state-metrics"
    spec:
      containers:
        - name: prometheus-kube-state-metrics
          image: "ist0ne/kube-state-metrics:v1.0.1"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: prometheus
    component: "kube-state-metrics"
  name: kube-state-metrics
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: prometheus
    component: "kube-state-metrics"
  type: "ClusterIP"          --
