apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "premium-lrs-eastus2"
  labels:
    app: prometheus
    component: prometheus
  name: PersistentVolumeClaimName
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
